import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    paddingTop: 0,
  },
  backgroundCircle: {
    position: 'absolute',
    top: 0,
    left: -200,
    height: 500,
    width: 800,
    borderBottomLeftRadius: 1000,
    borderBottomRightRadius: 1000,
    backgroundColor: '#3E4A3D',
  },
  flipContainer: {
    top: 20,
    width: 30,
    height: 30,
    padding: 20,
    marginBottom: 20,
    borderRadius: 40,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flipButton: {
    width: 23,
    height: 23,
    resizeMode: 'contain',
  },
  shadow: {
    position: 'absolute',
    top: 103,
    height: 500,
    width: '92%',
    borderRadius: 20,
    elevation: 5,
  },
  outerContainer: {
    position: 'absolute',
    top: 100,
    height: 500,
    width: '90%',
    padding: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 20,
  },
  frontView: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backView: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleContainer: {
    width: '100%',
    height: '10%',
    paddingHorizontal: 12,
    marginTop: '1%',
    marginBottom: '4%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  title: {
    width: '75%',
    height: '100%',
    resizeMode: 'contain',
  },
  pictureContainer: {
    width: '100%',
    height: '83%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
  },
  picture: {
    width: '100%',
    height: '90%',
    resizeMode: 'contain',
  },
  pictureFooter: {
    position: 'absolute',
    bottom: -3,
    paddingRight: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  withTtubeotContainer: {
    borderRadius: 100,
    backgroundColor: '#E3D6C5',
  },
  withTtubeot: {
    height: 40,
    width: 40,
    resizeMode: 'contain',
    borderRadius: 100,
  },
  footerText: {
    // bottom: -10,
  },
  journalTitleContainer: {
    borderBottomWidth: 1,
    width: '100%',
    height: '15%',
    paddingHorizontal: 10,
    borderColor: 'black',
  },
  journalTitle: {
    fontSize: 20,
  },
  journalContentContainer: {
    padding: 10,
    paddingTop: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '85%',
    flexWrap: 'wrap',
  },
  journalDetailSection: {
    margin: 10,
    width: '40%',
    height: '40%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'black',
  },
  journalDetail: {
    marginTop: 10,
  },
  journalDetailMap: {
    marginTop: 10,
    textDecorationLine: 'underline',
  },
  footPrintIcon: {
    width: 15,
    height: 22,
    resizeMode: 'contain',
  },
  backButton: {
    position: 'absolute',
    bottom: 120,
    padding: 10,
  },
  fullScreenButton: {
    position: 'absolute',
    bottom: 70,
    right: 10,
    padding: 5,
  },
  fullScreenButtonBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    borderRadius: 100,
    opacity: 0.5,
  },
  fullScreenIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
});

export default styles;
