import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  modalBackground: {
    justifyContent: 'flex-end',
    alignItems: 'center',
    flex: 1,
  },
  modalView: {
    width: '100%',
    height: '89%',
  },
  modalText: {
    fontSize: 18,
    textAlign: 'center',
  },
  titleBackContainer: {
    position: 'absolute',
    width: '104%',
    height: '100%',
    marginTop: 30,
    backgroundColor: '#DFD6C0',
  },
  titleBackImage: {
    width: '100%',
    height: 50,
    resizeMode: 'stretch',
  },
  titleImage: {
    width: '30%',
    height: 55,
    resizeMode: 'stretch',
  },
  title: {
    position: 'absolute',
    fontSize: 20,
    color: 'white',
    textAlign: 'center',
    top: 11,
  },
  titleContainer: {
    alignItems: 'center',
    marginVertical: 15,
    width: '100%',
  },
  menuContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  menu: {
    width: 110,
    height: 45,
    backgroundColor: '#C1A492',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: '#7A574B',
    borderStyle: 'solid',
    borderWidth: 2,
    borderBottomWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedMenu: {
    width: 110,
    height: 45,
    backgroundColor: '#FCF3EA',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: '#7A574B',
    borderStyle: 'solid',
    borderWidth: 2,
    borderBottomWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  menuText: {
    fontSize: 16,
    color: '#231514',
  },
  stitchedBorder: {
    position: 'absolute',
    width: '95%',
    height: '120%',
    top: 2,
    borderRadius: 6,
    borderBottomWidth: 0,
    borderColor: '#D0C8BD',
    borderWidth: 2,
    borderStyle: 'dashed',
    zIndex: -1,
  },
  itemContainer: {
    width: '100%',
    height: '50%',
    flex: 1,
    backgroundColor: '#EAE6DD',
  },
  item: {
    width: '96%',
    height: 130,
    backgroundColor: '#F2E6D6',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: '2%',
    marginVertical: '1%',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    elevation: 10,
  },
  itemInfoContainer: {
    flex: 0.75,
    flexDirection: 'column',
    gap: 10,
  },
  itemImageContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 7,
    borderWidth: 3,
    borderColor: '#8D6444',
  },
  itemImage: {
    width: 60,
    height: 60,
  },
  itemName: {
    fontSize: 16,
    color: '#231514',
  },
  itemDescription: {
    fontSize: 14,
    color: '#231514',
  },
  itemPriceContainer: {
    width: 85,
    height: 30,
    backgroundColor: '#CDC3B9',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemPriceInnerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: '#FDF4ED',
    borderRadius: 6,
    width: '90%',
  },
  itemPrice: {
    fontSize: 16,
    color: '#231514',
  },
  coinIcon: {
    width: 23,
    height: 23,
  },
  closeButton: {
    position: 'absolute',
    right: 15,
    top: 20,
  },
  progressBarContainer: {
    width: '100%',
    height: 24,
    backgroundColor: '#D4E6AD',
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 5,
    justifyContent: 'center',
    paddingVertical: '1%',
    paddingHorizontal: '2%',
    borderWidth: 3,
    borderColor: '#72563E',
    position: 'relative',
  },
  progressBar: {
    width: '95%',
    height: '90%',
    backgroundColor: '#B7C98E',
    borderRadius: 8,
  },
  progressText: {
    position: 'absolute',
    justifyContent: 'center',
    fontSize: 16,
    color: '#231514',
    alignSelf: 'center',
  },
  completeCheckBox: {
    width: 35,
    height: 35,
    borderWidth: 3,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completeCheck: {
    width: 25,
    height: 25,
    resizeMode: 'stretch',
  },
});
