import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  backGround: {
    flex: 1,
    backgroundColor: '#C7E5C4',
  },
  topThreeList: {
    width: '100%',
    height: '26%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
    gap: 10,
  },
  first: {
    width: '20%',
    height: '65%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#EBC11B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  second: {
    width: '20%',
    height: '45%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#D6CCA6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  third: {
    width: '20%',
    height: '30%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#E79E5E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rankingList: {
    width: '100%',
    backgroundColor: 'white',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 10,
  },
  rankingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 5,
    height: 80,
    paddingHorizontal: 5,
    marginHorizontal: '1%',
  },
  ranking: {
    width: '14%',
    fontSize: 24,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  rankingImage: {
    width: 60,
    height: 60,
  },
  rankingInfo: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '84%',
    backgroundColor: '#E6E6E6',
    borderRadius: 20,
    padding: '1%',
    paddingHorizontal: '5%',
  },
  rankingName: {
    width: '45%',
    fontSize: 18,
    textAlign: 'center',
  },
  rankingScore: {
    width: '25%',
    fontSize: 16,
    textAlign: 'right',
  },
  medal: {
    position: 'absolute',
    top: 0,
  },
  playerImage: {
    width: 55,
    height: 55,
    marginTop: 8,
  },
  playerName: {
    fontSize: 14,
    position: 'absolute',
    top: -30,
  },
  playerImageContainer: {
    position: 'absolute',
    top: -80,
    backgroundColor: 'white',
    borderRadius: 50,
    width: 65,
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
