import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  modalBackground: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // 어두운 배경 추가
  },
  modalView: {
    width: '100%',
    height: '89%',
  },
  modalText: {
    fontSize: 18,
    textAlign: 'center',
  },
  titleBackContainer: {
    position: 'absolute',
    width: '104%',
    height: '100%',
    marginTop: 30,
    backgroundColor: '#DFD6C0',
  },
  titleBackImage: {
    width: '100%',
    height: 50,
    resizeMode: 'stretch',
  },
  titleImage: {
    width: '30%',
    height: 55,
    resizeMode: 'stretch',
  },
  title: {
    position: 'absolute',
    fontSize: 20,
    color: 'white',
    textAlign: 'center',
    top: 11,
  },
  titleContainer: {
    alignItems: 'center',
    marginVertical: 15,
    width: '100%',
  },
  menuContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  menu: {
    width: 110,
    height: 45,
    backgroundColor: '#C1A492',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: '#7A574B',
    borderStyle: 'solid',
    borderWidth: 2,
    borderBottomWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedMenu: {
    width: 110,
    height: 45,
    backgroundColor: '#FCF3EA',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: '#7A574B',
    borderStyle: 'solid',
    borderWidth: 2,
    borderBottomWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  menuText: {
    fontSize: 16,
    color: '#231514',
  },
  stitchedBorder: {
    position: 'absolute',
    width: '95%',
    height: '120%',
    top: 2,
    borderRadius: 6,
    borderColor: '#D0C8BD',
    borderWidth: 1,
    borderStyle: 'dashed',
    zIndex: -1,
  },
  itemContainer: {
    width: '100%',
    height: '50%',
    flex: 1,
    backgroundColor: '#EAE6DD',
    paddingVertical: 5,
  },
  randomItem: {
    flex: 1,
    alignItems: 'center',
    width: '100%',
  },
  item: {
    width: '96%',
    height: 130,
    borderRadius: 10,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginHorizontal: '2%',
    marginVertical: '1%',
    padding: 20,
  },
  itemInfoContainer: {
    flex: 0.75,
    flexDirection: 'column',
    gap: 10,
  },
  itemImageContainer: {
    backgroundColor: 'white',
    borderRadius: 100,
    padding: 7,
    borderWidth: 5,
    borderColor: '#8D6444',
  },
  eggImageContainer: {
    flex: 1,
    width: '80%',
    alignItems: 'center',
    marginTop: 0, // 원하는 만큼 내려오게 설정
  },
  ttubeotWebview: {
    marginTop: 120,
    width: 500,
    height: 500,
    backgroundColor: 'transparent',
  },
  eggImage: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
    marginBottom: 10,
  },
  randomEggImage: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  itemImage: {
    width: 60,
    height: 60,
  },
  itemName: {
    fontSize: 16,
    color: '#231514',
  },
  itemDescription: {
    fontSize: 14,
    color: '#231514',
  },
  randomItemPriceContainer: {
    position: 'absolute',
    bottom: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemPriceContainer: {
    width: 100,
    height: 50,
    flexDirection: 'row',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemPrice: {
    fontSize: 16,
    color: '#231514',
  },
  coinIcon: {
    position: 'absolute',
    left: 10,
    justifyContent: 'center',
    width: 30,
    height: 30,
    zIndex: 1,
  },
  groupItem: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  groupContainer: {
    width: '92%',
    height: 180,
    elevation: 2,
    backgroundColor: '#DAD6CF',
    borderRadius: 20,
    marginVertical: 10,
    padding: 15,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    marginBottom: 20,
  },
  groupTitle: {
    marginLeft: 10,
    marginTop: 4,
    fontSize: 18,
  },
  groupPriceContainer: {
    marginTop: 4,
    marginRight: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  characterList: {
    flexDirection: 'row',
  },
  characterImageContainer: {
    width: 78,
    height: 78,
    borderRadius: 15,
    marginHorizontal: 5,
    backgroundColor: '#F4F3F1',
    opacity: 0.95,
    // elevation: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  choiceCharacterImageContainer: {
    width: 110,
    height: 110,
    borderRadius: 15,
    margin: 10,
    backgroundColor: '#F4F3F1',
    opacity: 0.95,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  characterImage: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
  },
  groupCoinIcon: {
    position: 'absolute',
    top: 7,
    left: 8,
    width: 25,
    height: 25,
    zIndex: 1,
  },
  choiceItem: {
    paddingBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  characterGrid: {
    width: '96%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  closeButton: {
    position: 'absolute',
    right: 15,
    top: 20,
  },
});
