import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  modalBackground: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // 어두운 배경 추가
  },
  modalView: {
    width: '100%',
    height: '89%',
    backgroundColor: '#F6F3EF',
    paddingTop: 20,
    paddingBottom: 10,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  modalBackgroundImage: {
    position: 'absolute',
    top: 0,
    width: '100%',
    height: 300,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    resizeMode: 'cover',
  },
  title: {
    position: 'absolute',
    fontSize: 20,
    color: 'white',
    textAlign: 'center',
    top: 13,
  },
  titleContainer: {
    alignItems: 'center',
    width: '100%',
    paddingBottom: 20,
  },
  titleImage: {
    width: '30%',
    height: 55,
    resizeMode: 'stretch',
  },
  closeButton: {
    position: 'absolute',
    top: 12,
    right: 12,
  },
  characterGrid: {
    marginTop: 0,
    alignSelf: 'center',
    justifyContent: 'flex-end',
  },
  characterColorImage: {
    width: 120,
    height: 120,
    margin: 5,
    borderRadius: 15,
    backgroundColor: '#E3D6C5',
  },
  characterBlackImage: {
    width: 120,
    height: 120,
    margin: 5,
    borderRadius: 15,
    backgroundColor: '#D3D3D3',
  },
  detailContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 0,
    height: '40%',
  },
  ttubeotInfoContainer: {
    width: '60%',
    right: 15,
    height: 200,
    borderRadius: 20,
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    opacity: 0.95,
    elevation: 3,
  },
  infoBackground: {
    width: '100%',
    height: 150,
    resizeMode: 'cover',
  },
  withInfoWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 25,
  },
  adventureCountContainer: {
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  adventureHatIcon: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
    marginBottom: 7,
    borderRadius: 100,
  },
  adventureCountTitle: {
    color: '#4E342E',
    marginBottom: 6,
    fontSize: 16,
  },
  adventureCount: {
    color: '#67514C',
  },
  footprintIcon: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
    marginBottom: 7,
    borderRadius: 100,
  },
  stepCountContainer: {
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  ttubeotWebview: {
    top: 50,
    left: 5,
    height: 190,
    backgroundColor: 'transparent',
  },
  ttubeotName: {
    fontSize: 20,
    marginTop: 20,
    alignSelf: 'center',
    marginBottom: 10,
  },
  undiscoveredContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '40%',
  },
  undiscoveredBox: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    opacity: 0.95,
    paddingHorizontal: 50,
    paddingVertical: 15,
    borderRadius: 25,
    elevation: 3,
  },
  undiscoveredTextWrapper: {
    alignItems: 'center',
    marginTop: 10,
  },
  breakUpDate: {
    color: '#6B6B6B',
    alignSelf: 'center',
    marginBottom: 10,
  },
  undiscoveredText: {
    fontSize: 16,
    marginVertical: 3,
  },
  sadEmoji: {
    fontSize: 20,
    marginTop: 5,
  },
});
